---
- hosts: apps
  become: yes
  tasks: 
    - name: Install vsftpd on App machines
      yum: name=vsftpd update_cache=yes state=latest
      ignore_errors: yes 
      notify: start vsftpd



  handlers: 
    - name: start vsftpd
      service: name=vsftpd enabled=yes state=started
